config/routes.rb
Cmsedits::Application.routes.draw do
  resources :repertoires

  resources :artists

  resources :concerts
  
  root :to => "concerts#index"

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_and_belongs_to_many :concerts
  
  
  def full_name
      "#{name_last}, #{name_first}"
  end

  
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  has_and_belongs_to_many :artists
end

app/models/repertoire.rb
class Repertoire < ActiveRecord::Base
  validates :composer, :presence => true
  validates :title, :presence => true
  validates :audio_file_name, :presence => true
  
  has_attached_file :audio
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /artists
  # GET /artists.xml
  def index
    @artists = Artist.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @artists }
    end
  end

  # GET /artists/1
  # GET /artists/1.xml
  def show
    @artist = Artist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.xml
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.xml
  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to(@artist, :notice => 'Artist was successfully created.') }
        format.xml  { render :xml => @artist, :status => :created, :location => @artist }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @artist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.xml
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to(@artist, :notice => 'Artist was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @artist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.xml
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to(artists_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  # GET /concerts
  # GET /concerts.xml
  def index
    @concerts = Concert.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @concerts }
    end
  end

  # GET /concerts/1
  # GET /concerts/1.xml
  def show
    @concert = Concert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @concert }
    end
  end

  # GET /concerts/new
  # GET /concerts/new.xml
  def new
    @concert = Concert.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @concert }
    end
  end

  # GET /concerts/1/edit
  def edit
    @concert = Concert.find(params[:id])
  end

  # POST /concerts
  # POST /concerts.xml
  def create
    @concert = Concert.new(params[:concert])

    respond_to do |format|
      if @concert.save
        format.html { redirect_to(@concert, :notice => 'Concert was successfully created.') }
        format.xml  { render :xml => @concert, :status => :created, :location => @concert }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @concert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /concerts/1
  # PUT /concerts/1.xml
  def update
    @concert = Concert.find(params[:id])

    respond_to do |format|
      if @concert.update_attributes(params[:concert])
        format.html { redirect_to(@concert, :notice => 'Concert was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @concert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.xml
  def destroy
    @concert = Concert.find(params[:id])
    @concert.destroy

    respond_to do |format|
      format.html { redirect_to(concerts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/repertoires_controller.rb
class RepertoiresController < ApplicationController
  # GET /repertoires
  # GET /repertoires.xml
  def index
    @repertoires = Repertoire.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @repertoires }
    end
  end

  # GET /repertoires/1
  # GET /repertoires/1.xml
  def show
    @repertoire = Repertoire.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @repertoire }
    end
  end

  # GET /repertoires/new
  # GET /repertoires/new.xml
  def new
    @repertoire = Repertoire.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @repertoire }
    end
  end

  # GET /repertoires/1/edit
  def edit
    @repertoire = Repertoire.find(params[:id])
  end

  # POST /repertoires
  # POST /repertoires.xml
  def create
    @repertoire = Repertoire.new(params[:repertoire])

    respond_to do |format|
      if @repertoire.save
        format.html { redirect_to(@repertoire, :notice => 'Repertoire was successfully created.') }
        format.xml  { render :xml => @repertoire, :status => :created, :location => @repertoire }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @repertoire.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /repertoires/1
  # PUT /repertoires/1.xml
  def update
    @repertoire = Repertoire.find(params[:id])

    respond_to do |format|
      if @repertoire.update_attributes(params[:repertoire])
        format.html { redirect_to(@repertoire, :notice => 'Repertoire was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @repertoire.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /repertoires/1
  # DELETE /repertoires/1.xml
  def destroy
    @repertoire = Repertoire.find(params[:id])
    @repertoire.destroy

    respond_to do |format|
      format.html { redirect_to(repertoires_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/repertoires_helper.rb
module RepertoiresHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_first %><br />
    <%= f.text_field :name_first %>
  </div>
  <div class="field">
    <%= f.label :name_last %><br />
    <%= f.text_field :name_last %>
  </div>
  <div class="field">
    <%= f.label :instrument %><br />
    <%= f.text_field :instrument %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Listing artists</h1>

<table>
  <tr>
    <th>Name first</th>
    <th>Name last</th>
    <th>Instrument</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @artists.each do |artist| %>
  <tr>
    <td><%= artist.name_first %></td>
    <td><%= artist.name_last %></td>
    <td><%= artist.instrument %></td>
    <td><%= link_to 'Show', artist %></td>
    <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
    <td><%= link_to 'Destroy', artist, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name first:</b>
  <%= @artist.name_first %>
</p>

<p>
  <b>Name last:</b>
  <%= @artist.name_last %>
</p>

<p>
  <b>Instrument:</b>
  <%= @artist.instrument %>
</p>


<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/concerts/_form.html.erb
<%= form_for(@concert) do |f| %>
  <% if @concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% @concert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <% Artist.all.each do |artist| %>
      <%= artist.full_name %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.select :artist, Artist.all.collect {|a| [a.full_name, a.id]}, {:order => 'full_name'} %>
  </div>
  <div class="field">
    <%= f.label :repertoire %><br />
    <%= f.text_field :repertoire %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date,
                          :prompt => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing concert</h1>

<%= render 'form' %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<h2>Concert List</h2>

<% @concerts.each do |concert| %>
  
    <h3><%=link_to concert.title, concert %></h3>
    <p><%= concert.artist %></p>
    <p><%= concert.date %></p>
    <ul>  
      <li><%= link_to 'Edit', edit_concert_path(concert) %></li>
      <li><%= link_to 'Destroy', concert, :confirm => 'Are you sure?', :method => :delete %></li>
    </ul>
<% end %>

<br />

<%= link_to 'New Concert', new_concert_path %>

app/views/concerts/new.html.erb
<h1>New concert</h1>

<%= render 'form' %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @concert.title %>
</p>

<p>
  <b>Artist:</b>
  <%= @concert.artist %>
</p>

<p>
  <b>Repertoire:</b>
  <%= @concert.repertoire %>
</p>

<p>
  <b>Date:</b>
  <%= @concert.date %>
</p>


<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CMSedits</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<h1>CMSedits</h1>
<nav>
  <ul>
    <li><%= link_to "Concerts", concerts_path %></li>
  </ul>
</nav>

<%= yield %>

</body>
</html>

app/views/repertoires/_form.html.erb
<%= form_for(@repertoire , :html => { :multipart => true }) do |f| %>
  <% if @repertoire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repertoire.errors.count, "error") %> prohibited this repertoire from being saved:</h2>

      <ul>
      <% @repertoire.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :composer %><br />
    <%= f.text_field :composer %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :audio %><br />
    <%= f.file_field :audio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repertoires/edit.html.erb
<h1>Editing repertoire</h1>

<%= render 'form' %>

<%= link_to 'Show', @repertoire %> |
<%= link_to 'Back', repertoires_path %>

app/views/repertoires/index.html.erb
<h1>Listing repertoires</h1>

<table>
  <tr>
    <th>Composer</th>
    <th>Title</th>
    <th>Audio file name</th>
    <th>Audio content type</th>
    <th>Audio file size</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @repertoires.each do |repertoire| %>
  <tr>
    <td><%= repertoire.composer %></td>
    <td><%= repertoire.title %></td>
    <td><%= repertoire.audio_file_name %></td>
    <td><%= repertoire.audio_content_type %></td>
    <td><%= repertoire.audio_file_size %></td>
    <td><%= link_to 'Show', repertoire %></td>
    <td><%= link_to 'Edit', edit_repertoire_path(repertoire) %></td>
    <td><%= link_to 'Destroy', repertoire, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Repertoire', new_repertoire_path %>

app/views/repertoires/new.html.erb
<h1>New repertoire</h1>

<%= render 'form' %>

<%= link_to 'Back', repertoires_path %>

app/views/repertoires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Composer:</b>
  <%= @repertoire.composer %>
</p>

<p>
  <b>Title:</b>
  <%= @repertoire.title %>
</p>

<p>
  <b>Audio file name:</b>
  <%= @repertoire.audio_file_name %>
</p>

<p>
  <b>Audio content type:</b>
  <%= @repertoire.audio_content_type %>
</p>

<p>
  <b>Audio file size:</b>
  <%= @repertoire.audio_file_size %>
</p>
<p>
  <b><%= link_to "Download", @repertoire.audio.url %></b>
</p>


<%= link_to 'Edit', edit_repertoire_path(@repertoire) %> |
<%= link_to 'Back', repertoires_path %>